"""
StyleSync Recent Outfits Component

Displays the grid of recent outfits generated by the AI stylist.
"""
import streamlit as st

def render_recent_outfits():
    """
    Renders a responsive 3-column layout showing the user's recent outfits.
    """
    st.write("### Recent Outfits")
    
    outfits = [
        {
            "name": "Smart Casual Blazer",
            "desc": "A sharp look pairing a tailored navy blazer with a crisp white t-shirt and charcoal chinos.",
            "emoji": "🧥",
            "tags": ["Semi-Formal", "Spring", "Work"]
        },
        {
            "name": "Cozy Weekend Knit",
            "desc": "A comfortable weekend outfit featuring an oversized cream knit sweater, light wash jeans, and clean white sneakers.",
            "emoji": "🧶",
            "tags": ["Casual", "Winter", "Relaxed"]
        },
        {
            "name": "Urban Edge Streetwear",
            "desc": "An edgy street style combining an olive bomber jacket, black graphic tee, distressed cargo pants, and leather boots.",
            "emoji": "👟",
            "tags": ["Casual", "Autumn", "Streetwear"]
        }
    ]
    
    cols = st.columns(3)
    
    for idx, outfit in enumerate(outfits):
        with cols[idx]:
            # Convert tags to HTML pills
            tags_html = "".join([f'<span class="outfit-tag">{tag}</span>' for tag in outfit["tags"]])
            
            st.markdown(
                f"""
                <div class="outfit-card">
                    <div class="outfit-image-placeholder">
                        {outfit["emoji"]}
                    </div>
                    <div class="outfit-details">
                        <h4 class="outfit-name">{outfit["name"]}</h4>
                        <p class="outfit-description">{outfit["desc"]}</p>
                        <div class="outfit-tags">
                            {tags_html}
                        </div>
                    </div>
                </div>
                """,
                unsafe_allow_html=True
            )
